'''
    Question:
The number generated by defense ranges from 0 to 20, and the value generated by attack ranges from 0 to 10.
When the value of defense is greater than the dexterity, it may make the attack value negative, which is logically problematic
Solutions are as follows:
Add a judgment statement to this process, set the attack value =0 when the attack-defense value <0

    Promotion:
The program is originally intended as a game, and the basic parameters are given by the system.
In order to increase the playability of the game, we can set up a mini-game. After completing the mini-game,
the user can +1 in the specified strength
'''
import random
class player:
	def __init__(self,strength,dexterity,constitution,intelligence,wisdom,charisma):
		self.strength = strength
		self.dexterity = dexterity
		self.constitution = constitution
		self.intelligence = intelligence
		self.wisdom = wisdom
		self.charisma = charisma

p1 = player(10,10,10,10,10,10)
print("strength="+str(p1.strength))
print("dexterity="+str(p1.dexterity))
print("constitution="+str(p1.constitution))
print("intelligence"+str(p1.intelligence))
print("wisdom="+str(p1.wisdom))
print("charisma="+str(p1.charisma))

hitpoints=p1.constitution*30+50
print("hitpoints="+str(hitpoints))
attack = random.randint(1,p1.strength)
print("attack="+str(attack))
defense = random.randint(1,20)
print("defense="+str(defense))
#在这个位置，提出了问题的解决方式，将攻击值可能为负数的情况排除
if defense>p1.dexterity:
	attack = attack-defense
if attack<0:
    attack = 0
print("attack="+str(attack))
heal = random.randint(1,20)
print("heal="+str(heal))
hitpoints = hitpoints + heal
print("hitpoints="+str(hitpoints))
#写一个猜数的小游戏，让用户完成一次后，可以在strength这一栏+1,不论输赢
import random
num = 1
yin_num = 0
shu_num = 0
while num <= 3:
    if shu_num == 2 or yin_num == 2:
        break
    user = int(input('请出拳 0（石头） 1（剪刀） 2（布）'))
    if user > 2:
        print('不能出大于2的值')
    else:
        data = ['石头', '剪刀', '布']
        com = random.randint(0, 2)
        print("您出的是{}，电脑出的是{}".format(data[user], data[com]))
        if user == com:
            print('平局')
            continue
        elif (user == 0 and com == 1) or (user == 1 and com == 2) or (user == 2 and com == 0):
            print('你赢了')
            yin_num += 1
        else:
            print('你输了')
    shu_num += 1
    num += 1
    p1.strength+=1
    break
print("你成功增加了你的天赋，现在你的天赋strength="+str(p1.strength))
